# Generated by Django 3.1.2 on 2020-10-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TejidoMama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parteP', models.IntegerField()),
                ('temp', models.FloatField()),
                ('color', models.FloatField()),
                ('inflamacion', models.FloatField()),
            ],
        ),
    ]
